language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t max/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true max/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-us-east-1-574691115259"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
